// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZQdzZ91gw7WdG88-bW2-q28qpQcHV_c4',
    appId: '1:909687691638:web:5dd5655bb8372c762b8257',
    messagingSenderId: '909687691638',
    projectId: 'briefnet-dde2d',
    authDomain: 'briefnet-dde2d.firebaseapp.com',
    storageBucket: 'briefnet-dde2d.appspot.com',
    measurementId: 'G-XC9CFBNK9S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0UafL4SbGn1NKh4CxqAOv8CRAJOmjHlg',
    appId: '1:909687691638:android:d085a4a0a929aede2b8257',
    messagingSenderId: '909687691638',
    projectId: 'briefnet-dde2d',
    storageBucket: 'briefnet-dde2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTPFVM2ENLubYQMgWnaPU74HcLTzpQqZ0',
    appId: '1:909687691638:ios:e7c9753956f8e27d2b8257',
    messagingSenderId: '909687691638',
    projectId: 'briefnet-dde2d',
    storageBucket: 'briefnet-dde2d.appspot.com',
    iosBundleId: 'com.example.briefnet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTPFVM2ENLubYQMgWnaPU74HcLTzpQqZ0',
    appId: '1:909687691638:ios:0185f955e33bc57a2b8257',
    messagingSenderId: '909687691638',
    projectId: 'briefnet-dde2d',
    storageBucket: 'briefnet-dde2d.appspot.com',
    iosBundleId: 'com.example.briefnet.RunnerTests',
  );
}
